# Country Analysis

In [1]:
import numpy as np
import pandas as pd

### Country Data Set and Info

In [2]:
df = pd.read_csv(r"..\datasets\Countries.csv")
df.head(10)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.0,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.0,...,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
9,Austria,Republic of Austria,Euro,Vienna,Western Europe,Europe,Austrian,47.333333,13.333333,26467.6,...,9042528,40.98360,3684288,5358240,5.10,8.29,Full democracy,39.0,Sebastian Kurz,Federal Chancellor

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [6]:
df.shape

(194, 64)

In [7]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

### Analysis Questions

In [8]:
# highest population 

df[df['population'] ==  df['population'].max()]['country']

75    India
Name: country, dtype: object

In [9]:
# capital of that country
# highest population 

df[df['population'] ==  df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [11]:
# least population 
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [12]:
# least population city
df[df['population'] == df['population'].min()]['capital_city']

179    Funafuti
Name: capital_city, dtype: object

In [ ]:
# highest democracy score 

df.sort_values(by='democracy_score',ascending=False)['country'].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [19]:
# total region 

df['region']

0           Southern Asia
1         Southern Europe
2         Northern Africa
3         Southern Europe
4           Middle Africa
              ...
189    South-Eastern Asia
190          Western Asia
191          Western Asia
192        Eastern Africa
193        Eastern Africa
Name: region, Length: 194, dtype: object

In [25]:
df['region'].value_counts()

region
Eastern Africa               17
Western Asia                 17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Northern Europe              10
Middle Africa                10
Eastern Europe               10
Western Europe                9
Southern Asia                 9
Central America               8
Northern Africa               6
Micronesia                    5
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [26]:
df['region'].value_counts().count()

np.int64(22)

In [28]:
# number of countries in eastern europe 

df['region'].value_counts()['Eastern Europe']

np.int64(10)

In [29]:
df[df['region'] == 'Eastern Europe']['country']

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: object

In [31]:
df.sample(10)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.0,24.0,258620.0,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
55,Estonia,Republic of Estonia,Euro,Tallinn,Northern Europe,Europe,Estonian,59.0,26.0,9850.0,...,1344768,25.74260,408688,936080,6.37,7.97,Flawed democracy,37.7,Jüri Ratas,Prime Minister
91,Lao PDR,Lao People's Democratic Republic,Lao kip,Vientiane,South-Eastern Asia,Asia,Laotian,18.0,105.0,20290.0,...,7529475,21.95120,4698995,2830480,1.21,2.37,Authoritarian,20.1,Bounnhang Vorachith,General Secretary of the Communist Party
178,Turkmenistan,Turkmenistan,New Turkmen manat,Ashgabat,Central Asia,Asia,Turkmen,40.0,60.0,338380.0,...,6430770,25.86210,2990694,3440076,0.92,1.72,Authoritarian,22.0,Gurbanguly Berdimuhamedow,President
188,Venezuela,República Bolivariana de Venezuela,Venezuelan bolivar fuerte,Caracas,South America,Americas,Venezuelan,8.0,-66.0,215000.0,...,28301696,22.15570,3289223,25012473,1.59,3.16,Authoritarian,24.2,Nicolás Maduro,President
132,Papua New Guinea,The Independent State of Papua New Guinea,Papua New Guinea kina,Port Moresby,Melanesia,Oceania,Papua New Guinean,-6.0,147.0,11900.0,...,10142619,1.73913,8765048,1377571,3.17,6.03,Flawed democracy,18.0,James Marape,Prime Minister
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.0,100.0,2154940.0,...,143555736,16.22220,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.4,...,10486941,46.41830,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
20,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina convertible mark,Sarajevo,Southern Europe,Europe,Bosnian,44.0,18.0,22160.0,...,3233526,16.66670,1621904,1611622,2.69,4.98,Hybrid regime,38.1,Valentin Inzko,High Representative
185,Uruguay,Oriental Republic of Uruguay,Uruguayan peso,Montevideo,South America,Americas,Uruguayan,-33.0,-56.0,140634.0,...,3422794,25.25250,147591,3275203,4.87,8.38,Full democracy,31.5,Luis Lacalle Pou,President